### PR TITLE
Complie jobs.generation.Utilities to jar file.

### PR DESCRIPTION
**Pull request by ragmani**
This PR is related to #9.
@hqueue @hseok-oh @chunseoklee PTAL

### CODE REVIEW

**Comment by hqueue** [comment]
It seems that current CI is working without this PR merged.
I'm somewhat confused. Can anyone explain why CI works without this PR now ?

**Comment by hseok-oh** [comment]
@hqueue CI now generates jobs using different repository: 
https://github.com/ragmani/netcore-jenkins.git
You can confirm this in root-generator configuration and console out.

We need to fix this to use this repository to generate jobs.

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by hqueue** [comment]
@hseok-oh I see. Thank you for the explanation :)

**Pull request merged**
