### PR TITLE
Update docker image with Tizen 4.0 M2

### PR DESCRIPTION
**Pull request by hqueue**
Becuase Tizen 4.0 M2 is released, update docker image
with Tizen 4.0 M2 rootfs to build dotnet.

https://developer.tizen.org/tizen/release-notes/tizen-4.0-public-m2
https://source.tizen.org/release/tizen-4.0-m2

Signed-off-by: Hyung-Kyu Choi <hk0110.choi@samsung.com>

### CODE REVIEW

**Comment by hqueue** [comment]
@ragmani PTAL and please check it works well in our CI.

**Comment by ragmani** [comment]
@hqueue It need to compile and create jobs.generation.classes.jar file to apply changing Utilities.groovy to CI. (ref. #10)
```
groovyc -d classes jobs/generation/Utilities.groovy
jar cvf jobs.generation.classes.jar -C classes/ .
```

**Comment by hqueue** [comment]
> @hqueue It need to compile and create jobs.generation.classes.jar file to apply changing Utilities.groovy to CI. (ref. #10)

@ragmani Thanks! I've update the PR with new `jar` file as suggested. 
Please take a look again.

**Comment by ragmani** [comment]
@hqueue LGTM

**Pull request merged**
