### PR TITLE
Set build with clang4.0 and update Docker image

### PR DESCRIPTION
**Pull request by gbalykov**
cc @ragmani @hqueue @alpencolt

### CODE REVIEW

**Comment by ragmani** [comment]
Sorry I'm late.
@hqueue Does that docker image support clang 4.0?

**Comment by hqueue** [comment]
I'm afraid not with old docker image and AFAIK @alpencolt is trying to prepare a new docker image.

**Review by hqueue — APPROVED** [review]
Code looks good to me.

@alpencolt If you have prepared a docker image with clang 4.0, then please feel free to merge this.

**Comment by gbalykov** [comment]
@hqueue @ragmani We have installed clang4.0 in current docker image. I think in near future we'll have to update it, as it is relatively old (ubuntu 14.04).

**Review by ragmani — APPROVED** [review]
LGTM

**Pull request merged**
